### ISSUE TITLE
console.debug doesn't exist node v6

### ISSUE THREAD

**Issue by mbsimonovic** [kallaspriit/ts-log#1]
so it does match the built-in console in node v8 and v10 but node v6 doesn't have console.debug. so perhaps just mention which node versions are supported (out-of-the-box).

**Comment by jsdevel** [comment]
or, @kallaspriit, would you accept a PR to make `debug` optional?  e.g.

change this:

```
  debug(message?: any, ...optionalParams: any[]): void;
```

to this:

```
  debug?(message?: any, ...optionalParams: any[]): void;
```

**Comment by kallaspriit** [comment]
Hey,

This would make "log.debug()" pretty unusable because TypeScript would make you first check whether it exists before you can use it.

![image](https://user-images.githubusercontent.com/277993/51822041-b6204700-22e3-11e9-87da-32810389fa7f.png)

Since node 6 is really old already (debug was actually added in node 8 but still) then I would not make the majority using newer version suffer.

Does that make sense?

**Comment by jsdevel** [comment]
What about adding a ConsoleLogger that delegates all methods to console?  We have to check if debug exists before passing console in later versions of node and assign log to debug which creates a lot of logic everywhere.

**Comment by kallaspriit** [comment]
I don't quite understand what You mean by "What about adding a ConsoleLogger that delegates all methods to console?".

If you want to log to built-in console, you can just directly pass it in as in the example.

```typescript
const calculator2 = new Calculator(console);
```

Or what do you mean, can You provide an example of how it should work?

**Comment by jsdevel** [comment]
@kallaspriit so we'd like to accept a `Logger`, but need to support every LTS version of node.  This requires clients to do this for node < 8:

```
if (!logger.debug) {
  logger.debug = logger.log;
}
```

**Comment by kallaspriit** [comment]
I think node <8 is old enough that making the life of everyone using newer versions harder for it is not worth it, closing this.

You're welcome to just copy the 20 odd lines to your project or fork the repository.
